project:
  type: website
  output-dir: docs
      
format: 
  html:
    highlight-style:
      light: "Breeze Light"
      dark: "Breeze Dark"
    toc: true
    theme: cosmo
    css: styles.css
    include-in-header:
      text: "<script src='https://code.jquery.com/jquery-3.7.1.slim.min.js'></script><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN' crossorigin='anonymous'><script type='module' src='/dark-mode-toggle.mjs'></script><script src='/jjcustom.js'></script>"
website:
  title: "Jeff's Rants"
  favicon: favicon.png
  navbar:
    pinned: true
    right:
      - text: "GU Homepage"
        icon: house
        href: "https://jpj.georgetown.domains"
      # - text: "<dark-mode-toggle id='theme-toggle' class='slider' appearance='toggle' permanent='true'></dark-mode-toggle>"
      #   href: "#"
execute: 
  warning: false
