project:
  type: website
  output-dir: docs
      
format: 
  html:
    theme: cosmo
    css: styles.css
website:
  title: "Jeff's Rants"
  navbar:
    right:
      - ""
  
execute: 
  warning: false
