---
title: "Mapping the Remnants of Colonialism"
author: "Jeff Jacobs"
bibliography: "../assets/data/Blog.bib"
format:
  gfm:
    keep-yaml: true
    title: ""
    author: ""
    date: ""
    excerpt-separator: <!--more-->
    preview-mode: raw
#format:
#  html:
#    preserve_yaml: true
#editor: visual
date: "2023-05-13"
embed-resources: true
layout: post
#always_allow_html: true
df-print: kable
code-copy: true
#toc: true
---

```{r,setup=TRUE,echo=FALSE}
knitr::opts_knit$set(base.dir = "C:\\Dropbox\\jpowerj.github.io\\", base.url = "/")
knitr::opts_chunk$set(fig.path = "../assets/img/")
# And, how many to display, for the top N/bottom N part
disp_n <- 5
```

A few years ago, in an era when I was wrestling with one of my more intense bouts of depression (an era where a "good" day would be one with "only" one or two panic attacks), grounding exercises were worth their weight in gold. One such exercise, which became somewhat of an obsession to this day, was the "Ultimate Geography Flashcards" package on Memrise. Long story short, it contains pretty much every territory in the world with some international-geopolitical relevance: UN-recognized countries, non-UN-recognized territories (Taiwan, Palestine, Somaliland), breakaway regions (Transnistria, Abkhazia), contested territories (Jammu and Kashmir), occupied territories (Golan Heights, Northern Cyprus), "overseas possessions" (French Guiana, Gibraltar), obscure Pacific islands, and more.<!--more-->

It made me realize that, whereas the public schools I went to mostly treated geography as a set of memorization exercises (you have 20 minutes to label all of the countries of Africa!), I honestly believe that it could be used as a window into some of the most important historical events---active and frozen conflicts, international disputes, etc.---which explain how the world got the way it is today.

So, with that in mind, today I decided to map out all the territories in the world I could think of that represent "remnants" of colonialism. Colonialism is often treated as something in the past, that we've "moved on" from, but then... what is Puerto Rico? Why does Liberia's flag look so similar to the United States'? Why is there a region of South America that is part of the EU and uses the Euro? Why are there regions of India where Portuguese, French, and other European languages are still spoken? Why do so many countries outside of South Asia have a humongous South Asian population---Singapore, Fiji, Guyana? Why are there random Dutch-speaking white communities in Sri Lanka? German-speaking white communities in Jamaica?[^orizio]

## The Map

```{=html}
<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1sYF9ON0-6zXKSdxbgKD_vOCf_Olxrr0&ehbc=2E312F" width="100%" height="480"></iframe>
```

## Relevance to the World Today

[^orizio]: The latter two cases come from a super fascinating book by Riccardo Orizio, a journalistic account of his attempts to find these communities, called *Lost White Tribes: The End of Privilege and the Last Colonials in Sri Lanka, Jamaica, Brazil, Haiti, Namibia, and Guadeloupe* @orizio_lost_2001

## References

::: {#refs}
:::