name: scp to gtown domains
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GU_HOST }}
        username: ${{ secrets.GU_USERNAME }}
        password: ${{ secrets.GU_PASSWORD }}
        port: 22
        source: "dist_static/*"
        target: "/home/jpjgeorg/public_html/"
        strip_components: 1
        overwrite: true

