name: scp to stanford xenon
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SU_HOST }}
        username: ${{ secrets.SU_USERNAME }}
        password: ${{ secrets.SU_PASSWORD }}
        port: ${{ secrets.SU_PORT }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
        #passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
        source: "docs_su/*"
        target: ${{ secrets.SU_PATH }}
        strip_components: 1
        overwrite: true

