name: scp to stanford
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SU_HOST }}
        username: ${{ secrets.SU_USERNAME }}
        password: ${{ secrets.SU_PASSWORD }}
        port: 22
        source: "dist_static/*"
        target: "/afs/cs.stanford.edu/u/jjacobs3/www/"
        strip_components: 1
        overwrite: true

